NODE_BIN=./node_modules/.bin
DIFF_COVER_BASE_BRANCH=master

.PHONY: clean help migrate prod_requirements quality requirements serve static test validate

help:
	@echo "Please use \`make <target>\` where <target> is one of"
	@echo "  clean                      delete generated byte code and coverage reports"
	@echo "  help                       display this help message"
	@echo "  migrate                    apply database migrations"
	@echo "  prod_requirements          install production requirements for text_reader python3 environment"
	@echo "  requirements               install local requirements for text_reader python3 environment"
	@echo "  serve                      serve text_reader App at 0.0.0.0:9999"
	@echo "  static                     build and compress static assets"
	@echo ""

clean:
	find . -name '*.pyc' -delete
	coverage erase

requirements:
	pip install -qr requirements/local.txt --exists-action w

prod_requirements:
	pip install -qr requirements/production.txt --exists-action w

static:
	python manage.py collectstatic --noinput

serve:
	python manage.py runserver 0.0.0.0:9999

migrate:
	python manage.py migrate --noinput

validate: quality test

test: test
